import fs from "node:fs";

const output = new URL("./generated", import.meta.url);
fs.rmSync(output, { recursive: true, force: true });
fs.mkdirSync(output);
fs.writeFileSync(
  new URL("./generated/build-info.txt", import.meta.url),
  "generated by the demo build\n",
);
